/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAuthenticationRouteImport } from './routes/_app/_authentication'
import { Route as AppSystemIndexRouteImport } from './routes/_app/_system/index'
import { Route as AppSystem403RouteImport } from './routes/_app/_system/403'
import { Route as AppSystemSplatRouteImport } from './routes/_app/_system/$'
import { Route as AppAuthenticationRemindRouteImport } from './routes/_app/_authentication/remind'
import { Route as AppSystemIframeSlugRouteImport } from './routes/_app/_system/iframe/$slug'
import { Route as AppAuthenticationDemoUsersRouteImport } from './routes/_app/_authentication/demo/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticationRoute = AppAuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemIndexRoute = AppSystemIndexRouteImport.update({
  id: '/_system/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystem403Route = AppSystem403RouteImport.update({
  id: '/_system/403',
  path: '/403',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSplatRoute = AppSystemSplatRouteImport.update({
  id: '/_system/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthenticationRemindRoute = AppAuthenticationRemindRouteImport.update({
  id: '/remind',
  path: '/remind',
  getParentRoute: () => AppAuthenticationRoute,
} as any)
const AppSystemIframeSlugRoute = AppSystemIframeSlugRouteImport.update({
  id: '/_system/iframe/$slug',
  path: '/iframe/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthenticationDemoUsersRoute =
  AppAuthenticationDemoUsersRouteImport.update({
    id: '/demo/users',
    path: '/demo/users',
    getParentRoute: () => AppAuthenticationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppSystemIndexRoute
  '/login': typeof LoginRoute
  '/remind': typeof AppAuthenticationRemindRoute
  '/$': typeof AppSystemSplatRoute
  '/403': typeof AppSystem403Route
  '/demo/users': typeof AppAuthenticationDemoUsersRoute
  '/iframe/$slug': typeof AppSystemIframeSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppSystemIndexRoute
  '/remind': typeof AppAuthenticationRemindRoute
  '/$': typeof AppSystemSplatRoute
  '/403': typeof AppSystem403Route
  '/demo/users': typeof AppAuthenticationDemoUsersRoute
  '/iframe/$slug': typeof AppSystemIframeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_authentication': typeof AppAuthenticationRouteWithChildren
  '/_app/_authentication/remind': typeof AppAuthenticationRemindRoute
  '/_app/_system/$': typeof AppSystemSplatRoute
  '/_app/_system/403': typeof AppSystem403Route
  '/_app/_system/': typeof AppSystemIndexRoute
  '/_app/_authentication/demo/users': typeof AppAuthenticationDemoUsersRoute
  '/_app/_system/iframe/$slug': typeof AppSystemIframeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/remind' | '/$' | '/403' | '/demo/users' | '/iframe/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/login' | '/' | '/remind' | '/$' | '/403' | '/demo/users' | '/iframe/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_authentication'
    | '/_app/_authentication/remind'
    | '/_app/_system/$'
    | '/_app/_system/403'
    | '/_app/_system/'
    | '/_app/_authentication/demo/users'
    | '/_app/_system/iframe/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authentication': {
      id: '/_app/_authentication'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_system/': {
      id: '/_app/_system/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppSystemIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_system/403': {
      id: '/_app/_system/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof AppSystem403RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_system/$': {
      id: '/_app/_system/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSystemSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authentication/remind': {
      id: '/_app/_authentication/remind'
      path: '/remind'
      fullPath: '/remind'
      preLoaderRoute: typeof AppAuthenticationRemindRouteImport
      parentRoute: typeof AppAuthenticationRoute
    }
    '/_app/_system/iframe/$slug': {
      id: '/_app/_system/iframe/$slug'
      path: '/iframe/$slug'
      fullPath: '/iframe/$slug'
      preLoaderRoute: typeof AppSystemIframeSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authentication/demo/users': {
      id: '/_app/_authentication/demo/users'
      path: '/demo/users'
      fullPath: '/demo/users'
      preLoaderRoute: typeof AppAuthenticationDemoUsersRouteImport
      parentRoute: typeof AppAuthenticationRoute
    }
  }
}

interface AppAuthenticationRouteChildren {
  AppAuthenticationRemindRoute: typeof AppAuthenticationRemindRoute
  AppAuthenticationDemoUsersRoute: typeof AppAuthenticationDemoUsersRoute
}

const AppAuthenticationRouteChildren: AppAuthenticationRouteChildren = {
  AppAuthenticationRemindRoute: AppAuthenticationRemindRoute,
  AppAuthenticationDemoUsersRoute: AppAuthenticationDemoUsersRoute,
}

const AppAuthenticationRouteWithChildren =
  AppAuthenticationRoute._addFileChildren(AppAuthenticationRouteChildren)

interface AppRouteChildren {
  AppAuthenticationRoute: typeof AppAuthenticationRouteWithChildren
  AppSystemSplatRoute: typeof AppSystemSplatRoute
  AppSystem403Route: typeof AppSystem403Route
  AppSystemIndexRoute: typeof AppSystemIndexRoute
  AppSystemIframeSlugRoute: typeof AppSystemIframeSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticationRoute: AppAuthenticationRouteWithChildren,
  AppSystemSplatRoute: AppSystemSplatRoute,
  AppSystem403Route: AppSystem403Route,
  AppSystemIndexRoute: AppSystemIndexRoute,
  AppSystemIframeSlugRoute: AppSystemIframeSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
